
global proc drag_and_drop_install() {
    string $whatIs = `whatIs drag_and_drop_install`;
    string $path = `substring $whatIs 25 999`;
    string $sourceLocation = `substitute "drag_and_drop_install.mel" $path ""`;
    python("import sys");
    python("sys.path.append('" + $sourceLocation + "')");
    python("import hko_mm_hotkeys");
    python("reload(hko_mm_hotkeys)");
    python("hko_mm_hotkeys._onMayaDropped()");
}

drag_and_drop_install();
