
global proc drag_and_drop_install() {
    string $whatIs = `whatIs drag_and_drop_install`;
    string $path = `substring $whatIs 25 999`;
    string $sourceLocation = `substitute "drag_and_drop_install.mel" $path ""`;
    python("import sys");
    python("sys.path.append('" + $sourceLocation + "')");
    python("import mayaMatchmoveTools");
    python("reload(mayaMatchmoveTools)");
    python("mayaMatchmoveTools._onMayaDropped()");
}

drag_and_drop_install();
